### PR TITLE
Fix repository location

### PR DESCRIPTION
**Pull request by krzysiekpiasecki**

### CODE REVIEW

**Comment by christianesperar** [comment]
There is special changes on this repository that needed to make bootstrap-daterangepicker compatible with older version. Do you have any kind of problem encounter on this version?

**Comment by krzysiekpiasecki** [comment]
Cannot make a fresh install - access denied. Should the location be point with http protocol?

**Comment by christianesperar** [comment]
Can you take screenshot of the actual error?

**Comment by krzysiekpiasecki** [comment]
I fix it on my 'side'.

**Pull request closed without merging**
