### PR TITLE
Remove role attr from nav element

### PR DESCRIPTION
**Pull request by krzysiekpiasecki**
Role attribute "navigation" is not necessary for nav element.

### CODE REVIEW

**Comment by krzysiekpiasecki** [comment]
There is also a lot of empty class attributes in the source code.

**Comment by christianesperar** [comment]
Yup, that's right there are so many cleanup to do on this themes. We can merge this after some PR is merge.

**Comment by christianesperar** [comment]
Please make sure this will added to all pages including new page

**Comment by christianesperar** [comment]
Please reopen this in order to merge. Thanks!

**Comment by krzysiekpiasecki** [comment]
You've close it. How can I reopen?

**Comment by christianesperar** [comment]
I accidentally close it, can you just submit new pr if you can't also open it? Thanks!

**Pull request closed without merging**
